site_name: Bhukamatha User Guide
site_url: https://example.com/

repo_url: https://github.com/surveyorstories/bhukamatha
repo_name: Surveyorstories/bhukamatha
copyright: Copyright © 2023 Surveyor Stories.


nav:
  - Installation: index.md
  - Getting Started : getting-started.md




theme:
  name: material
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
    - navigation.path
    
    

  palette:


    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default 
      primary: lime
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: lime
      #accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  

  font:
    text: Montserrat
    code: Source Code Pro
  favicon: icon.png
  logo: icon.png


plugins:
  - mike
  - tags
  - search:
      lang: en
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - with-pdf:
  #       author: Surveyor Stories
  #       copyright: Copyright © 2023 Surveyor Stories.
  #       #
  #       cover: true
  #       cover_subtitle: Version 1.0.3 Beta
  #       cover_logo : file:///D:\\BHUKAMATHA_PROJECT\\my-project\\assets\\icon.png #file:///D:\\R-Lpms\\test\\modeltest\\svg\\SVG\\icon.png
  #       #back_cover: true
  #       #cover_title: Bhukamatha User Guide
  #       #cover_subtitle: SUBTITLE TEXT
  #       #custom_template_path: TEMPLATES PATH
  #       #
  #       toc_title: Index
  #       heading_shift: true
  #       toc_level: 3
  #       #ordered_chapter_level: 2
  #       #excludes_children:
  #       #    - 'release-notes/:upgrading'
  #       #    - 'release-notes/:changelog'
  #       #
  #       #exclude_pages:
  #       #    - 'bugs/'
  #       #    - 'appendix/contribute/'
  #       convert_iframe:
  #           - src: IFRAME SRC
  #             img: POSTER IMAGE URL
  #             text: ALTERNATE TEXT
  #           #- src: ...
  #       #two_columns_level: 3
  #       #
  #       render_js: true
         
  #       headless_chrome_path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"  
      
  #       #output_path: any-place/document.pdf
  #       #enabled_if_env: ENABLE_PDF_EXPORT
  #       #
  #       #debug_html: true
  #       show_anchors: true
  #       verbose: true
  


  

# Customization
extra:
  version:
    provider: mike
  #generator: false

 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/surveyorstories/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@surveyorstories

    - icon: fontawesome/brands/telegram
      link: https://t.me/surveyorstories
  

extra_css:
  - assets/extra.css
extra_javascript:
  - javascripts/extra.js


markdown_extensions:
  - toc:
      permalink: true
    
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences